project:
  type: website

website:
  title: "Gabe Sekeres"
  twitter-card: true
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd
      - ws.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



