---
title: "About"
---
Hi! thanks for visitng my site. I've tried to compile some resources for students interested in pursuing economics as predoc and more generally in post-secondary education in my resources page. Here, I'll talk a little bit about myself. 

I'm a predoc at Stanford, where I'm working on a medical debt relief project with Neale Mahoney. I'm interested in health economics, public finance, and household finance. 

When I'm not working, I powerlift (which I've been doing one and off for the past 3 years). I also donate blood with the [Stanford Blood Center](https://sbcdonor.org/donor/schedules/zip) as often as I am eligible and would encourage anyone who is eligible to consider doing so as well. Being a consistent donor can be especially helpful for patients who receive frequent blood transfusions and need a good match on antibodies outside of (A, B, O, Rh +/-). 

I attended Wellesley College, a historically women's college, where I majored in economics and math.
At Wellesley, I explored cs, sociology, and philosophy before landing on econ and math. 