---
title: "Research"
---


## Peer-Reviewed Publications

 - Dixit, A., __Sekeres, G.__, Mariano, E., Memtsoudis, S., and Sun, E. (2023) ["Association of Patient Race and Hospital with Utilization of Regional Anesthesia for Treatment of Post-Operative Pain in Total Knee Arthroplasty: A Retrospective Analysis Using Medicare Claims."](https://pubs.asahq.org/anesthesiology/article-abstract/doi/10.1097/ALN.0000000000004827/139375/Association-of-Patient-Race-and-Hospital-with?redirectedFrom=fulltext) _Anesthesiology_. doi: [10.1097/ALN.0000000000004827](https://doi.org/10.1097/ALN.0000000000004827)
 
 
## Under Review

 - Parameswaran, G., __Sekeres, G.__, and Goldblatt, H. "The Politics of the Slippery Slope." R & R at the _Journal of Politics_.

 - __Sekeres, G.__, Miller, T., Mariano, E., Glance, L., and Sun, E. "Correlation Between Anesthesia Group Size and Merit-Based Incentive Payment System (MIPS) Scores." R & R at _Anesthesiology_.
 
 
## Working Papers

 - [A New Theory on Plea Bargains in Criminal Procedure](/plea_bargains_current.pdf) (also my PhD writing sample)
 
 Abstract: I present a new model of plea bargaining before criminal trials. Two specific modifications are made from the canonical models (Bebchuk (1984) and Reinganum (1988)) -- I assume that the defendant's inherent guilt is immaterial to the trial outcome, instead relying only on the evidence available to be presented, and I assume that the prosecutor knows the true value of the evidence while the defendant knows only the bounds. I find that the decisions in equilibrium rely mainly on the maximum possible evidence the prosecutor _could_ have, rather than the evidence they _actually_ have. This result implies that plea bargains do not effectively sort innocent and guilty defendants. 

 - __Sekeres, G.__, [The Effects of Communication on a Middle Equilibrium in Prisoner's Dilemma](/gabe_sekeres_thesis.pdf). 2022. (Senior Thesis)
 
## Currently Thinking About 
 
 - Cross-time Empirical Revealed Preferences: This is very much in the conception stage, but I think there's something to the idea of implied continuity of preferences over time (_i.e._, continuously changing preferences derived from discrete observations of preferences). I'm doing PhD apps this semester, though, so this is on the back burner.
 
 - Networks of information sharing re: medical knowledge over time -- how fast does is spread, where does it go, when do independent discoveries become merged. Thinking about this with [Marissa Hindelang](https://www.linkedin.com/in/marissa-hindelang/?originalSubdomain=es)
 
 