---
title: "Resources"
---

## Pre-Doc Advice and Resources
Smarter people have already said a lot of what I think needs to be said. I've included a ton of links + some original advice below.

- [EconRA Guide](https://raguide.github.io/): Covers all steps of the predoc process. Highly recommend reading through.

- [Alvin Christian's Advice](https://www.alvinchristian.com/resources): Advice from a recent predoc.

- [Women in Econ and Policy Pre-Doc Advice Compilation](https://us17.campaign-archive.com/?u=3d315482a01ddd29e7b7161ac&id=0c0e1b3460)

- [Predoc.org](https://predoc.org/): You might've heard of this. I used it mostly to look for jobs. They host coding and other kinds of workshops that can be helpful.

- [Predoc survey](https://z-y-huang.github.io/predoc_survey/slides.pdf): Useful statistics on the industry

- Talk to previous predocs of the person who you want to work for and ask about work hours, expectations, stress, & general environment.

  - How many hours a week did they work on average?

  - How reasonable did they feel like the deadlines were?

  - How often did they meet with their PI to talk about their own research ideas, professional growth etc.?

  - Is there any predoc cohort / how much interaction do they have with other predocs at the institution?

  - What is their physical office like? Are there windows? How often are they expected to work in person versus remote?

  - How is the salary / stipend structured? Were they paid on time? How much of their stipend did they spend on rent?

  - What is health insurance like? Who covers the premium?

  - What opportunities do they have to take graduate-level classes during their predoc? Do they have to cover the cost? Is it for a grade or can they only audit?

  - What graduate programs did the previous predocs end up in?

  - What are the norms around co-authorship with predocs? How will your work be recognized?

    - The norms within econ don't match up with other fields. In some fields, it is the norm for RAs who contribute a significant amount of time to a project to become co-authors. In econ, this view is often discounted in favor of predocs remaining in the acknowledgements. Here are some interesting discussions of this phenomenon: [1](https://twitter.com/straightedge/status/1312636836771033089), [2](https://twitter.com/jonj/status/1354171126386208768)

  - Ask if any of their friends have had a particularly good or bad experiences with certain professors.


### Finding Jobs

- [Predoc.org](https://predoc.org/opportunities) and its [Twitter](https://twitter.com/predoc_org)

- [NBER](https://www.nber.org/career-resources/research-assistant-positions-not-nber) (be sure to check both opportunities at the NBER and outside of it)

- [Econ RA twitter](https://twitter.com/econ_ra)

  - Sometimes this account is a little delayed in retweeting things, I would just search @econ_ra on Twitter to see opportunities that @ them.

- [Econ Job Market](https://econjobmarket.org/market) usually skews towards more international positions.

- [Fed Econ Jobs](https://www.fedeconjobs.org/Branches/AllOpportunities.aspx) it's surprisingly hard to find this website on google, but it contains a lot of good information if you are interested in RA-ing at the Fed.

- There are certain programs that regularly hire some RAs. Here are a couple:

  - [PhD Excellence Initiative](https://www.peterblairhenry.com/phd-excellence-initiative/)

  - [SIEPR (Stanford)](https://siepr.stanford.edu/programs/predoctoral-research-fellowship-opportunities)

  - [Tobin (Yale)](https://tobin.yale.edu/programs/pre-doctoral-fellows-program/apply)

  - [Innovations for Poverty Action](https://www.poverty-action.org/work-with-ipa/current-opportunities)

  - [J-PAL](https://www.povertyactionlab.org/careers)

  - [Microsoft Research New England](https://www.microsoft.com/en-us/research/group/microsoft-research-pre-doctoral-research-assistant-program/)

  - [NYU Stern](https://www.stern.nyu.edu/programs-admissions/phd/academics/pre-doctoral-program)

  - [Columbia Business School](https://academics.gsb.columbia.edu/predoctoral-research/predoctoral-fellows-program)

  - [Stanford GSB](https://www.gsb.stanford.edu/programs/research-fellows)

  - [EPIC UChicago](https://epic.uchicago.edu/about/jobs-fellowships/fellowships/predoctoral-fellowship-program/)

  - [Becker Friedman Institute](https://bfi.uchicago.edu/info-for/prep/)

  - [Kellogg](https://www.kellogg.northwestern.edu/research-support/research-fellows.aspx)

  - [Harvard Business School](https://www.hbs.edu/predoctoral)

  - [Fama Miller](https://research.chicagobooth.edu/famamiller/research/research-professionals)

  - [Chicago Booth](https://www.chicagobooth.edu/faculty/research-staff)

  - [Opportunity Insights](https://opportunityinsights.org/joinourteam/)

  - [King Center, Stanford](https://kingcenter.stanford.edu/opportunities/prospective-predoctoral-research-fellows)

  - [Council of Economic Advisers](https://www.whitehouse.gov/cea/work-for-us/research-assistant/)

  - [Consumer Financial Protection Bureau](https://www.consumerfinance.gov/about-us/careers/students-and-graduates/)

  - [DOJ Antitrust](https://www.justice.gov/atr/employment-opportunities-research-analysts)

  - [Columbia Bridge to PhD](https://bridgetophd.facultydiversity.columbia.edu/)

  - [Michigan Bridge to PhD](https://michiganross.umich.edu/programs/phd/bridges-program)

### My experience
A little info on my timeline (I applied in the fall of 2021). I started applying to predocs in mid-September. I talked to current and former predocs through the end of September. I did my first coding task at the end of September, and I made my decision during the first half of October.

  - Stipend 58.5k

    - The stipend is deposited quarterly -- the beginning of work was in early July but most people in my cohort were paid for the first time on July 30th.

    - I spent 1.05k on rent last year and now am spending 2.1k this year.

  - [Health insurance](https://vaden.stanford.edu/insurance-referral-office/cardinal-care-overview-benefits) with SIEPR covering the premium. I find that I dont pay more than $20 for routine services and $100 for ER services. There is a hospital on campus which is nice.

  - One grad course per quarter at Stanford covered by SIEPR (excluding summer).

  - Work laptop

  - Access to on campus housing

    - In practice, this isn't quite correct; no predocs in my cohort got fall housing on-campus through Stanford's lottery.
    I would say for myself, one of the more stressful parts of the job is getting housing/ moving multiple times within a year and not really knowing that this would happen beforehand.

  - Access to on campus amenities like libraries, gym etc.

  - Mentoring

  - Predoc programming

  - 20 leave days and 10 holidays. Leave days are not guaranteed but negotiated with professor.

  - J-1 visa sponsorship / OPT eligible (I am not an international predoc, so I know less about how this works in practice)


## Undergrad Advice
I am afraid that anything I say will look utterly naive as someone who is just finishing undergrad myself. The only useful resource I have here is the graduate school advice I looked at to get a sense of what classes I should take now.

- [Susan Athey's Advice](https://athey.people.stanford.edu/professional-advice)

- [Alvin Christian's Advice](https://drive.google.com/file/d/1QozD6_4_bvMd2o-q-yh9Doc5aQ6i3nPV/view)

- For more grad school specific advice look [here](https://sites.google.com/view/econgradadvice/).

- The most helpful places will be looking at the university that you are interested in and seeing if they have information about 'ideal' candidates in their application sections. Some are more explicit than others with respect to expected classes etc.

- Alex Albright's [Thesis Advice](https://thelittledataset.com/undergrad-thesis-resources/)

### My Setup

- Things I use everyday

  - [GitHub](https://missing.csail.mit.edu/2020/version-control/) to implement version control with your code.
    - I use [Tower](https://www.git-tower.com/mac) (included in [Student Developer Pack](https://education.github.com/pack)) to make interacting with GitHub less icky.

  - If you use [Overleaf](https://www.overleaf.com) set up Dropbox integration.

    - I prefer [Texifier](https://www.texifier.com/) (better UI). Can edit documents through Dropbox so it also updates on Overleaf.

  - [Zotero](https://www.zotero.org/support/quick_start_guide) for citation management.

  - There's a lot of value in listening to your essays before you submit them. I use [Kurzweil 300](https://www.kurzweil3000.com) (provided through my college's disability office) to do so.

  - [GoodNotes](https://goodnotes.com/) (enable some kind of syncing so you don't risk losing your notes)

  - I prefer the simplicity of [Obsidian](https://obsidian.md/) over [Notion](https://www.notion.so/)

  - [Privacy Badger](https://privacybadger.org/)

  - [1Password](https://1password.com/)

  - [Libby](https://libbyapp.com) (app). Borrow free audiobooks from your library! Really nice UI.

- Portable ergonomic equipment (good for hand/arm pain)

  - [Nextstand](https://nexstand.io/) (h/t [Nic](https://njw.fish/))

  - [Microsoft Sculpt](https://www.microsoft.com/en-us/d/microsoft-sculpt-ergonomic-desktop/8xk02kz6k69w?activetab=pivot:overviewtab) or [Kyria](https://splitkb.com/products/kyria-pcb-kit?variant=42433243218179)

  - [Logitech MX Master 3](https://www.logitech.com/en-us/products/mice/mx-master-3.910-005647.html)

## Coding & Data Visualization

This doesn't cover any basic stata/R tutorials; these are just some tools I've used in the past.

- [Datawrapper](https://www.datawrapper.de/) is a really cool no-code tool. I generally like to use R to make visualizations but this automatically creates good-looking graphs that are especially useful in presenting summary data.

- [Easily make Tikz Diagrams](https://www.mathcha.io/)

- [Stata2R](https://stata2r.github.io/) Learning R if you know Stata.

- [Quant Econ](https://quantecon.org/lectures/) Python and Julia for Econ.

- I used [Quarto](https://quarto.org/docs/websites/) and [Netlify](https://www.netlify.com/) to build this website.

- [Fantastical](https://flexibits.com/fantastical) Now that I have five emails, its nice being able to have all of the calendars in one place + good UI for scheud
